# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 004650f77f7148f048cbab2e07229a0723a941e6ac9714e7fe647c278cc7b9c673446805c73d5b1c671bc84e120d36accc9eff1a372e991fddfa41f20158ba14

test:
  secret_key_base: 4632df1477dd919382cc6a22c743702018a1275f3a1c61b82d82c6d8350de4ef8dff6f8f7e82cbb37305cf403bd44f095fb75cbdab0eccc6d362a02aca809b24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
